### ISSUE TITLE
Add padding for narrower displays

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#10]
**Issue**
On narrow enough displays, the content goes all the way to the edge of the display. This always results in complaints from users about the content being difficult to read.

![screenshot 2017-01-30 10 51 30](https://cloud.githubusercontent.com/assets/1282401/22432610/1664b4e4-e6db-11e6-928d-c52b107ba462.png)

**Proposed solution**
Add `padding-left: 20px; padding-right: 20px;` to `header`, `main` and `footer`.

![screenshot 2017-01-30 10 53 20](https://cloud.githubusercontent.com/assets/1282401/22432596/08d05fea-e6db-11e6-86e3-a31995654f18.png)

**Comment by adamdelaney** [comment]
I think `.container { padding-left: 20px; padding-right: 20px; }` should take care of this problem
