### ISSUE TITLE
Footer covered by IPE buttons

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#11]
On panel pages (People, Events, Articles, front page), the IPE button bar covers the UI Bar footer.

![screenshot 2017-01-30 11 01 40](https://cloud.githubusercontent.com/assets/1282401/22432741/8199bae8-e6db-11e6-9e2b-c3c24afaf8fe.png)

**Comment by genjohnson** [comment]
For comparison, this is how the footer and IPE button bar look in the Black & Gold theme.

![screenshot 2017-01-30 11 02 51](https://cloud.githubusercontent.com/assets/1282401/22432796/ba1e2520-e6db-11e6-921d-d38e3afd0296.png)

**Comment by adamdelaney** [comment]
We could do something like this:
`.panels-ipe .l-page { padding-bottom: 59px }`
