### ISSUE TITLE
"Filter by Department" block is missing styles

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#12]
I would expect the "Filter by Department" block to be styled similarly to the "Filter by Type" block.
![screenshot 2017-01-30 11 15 23](https://cloud.githubusercontent.com/assets/1282401/22433288/7f90ff34-e6dd-11e6-820f-a5ce17d32761.png)

**Comment by bspeare** [comment]
I have updated the styles to include the "filter by department" block.
