### ISSUE TITLE
Add bottom margin to items in People Grid

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#13]
**Issue*
There's no `margin-bottom` set for the view rows of the People Grid List, which causes the items to run together. (This isn't as noticeable when the Bio field is included in the display because paragraphs have bottom margin.)
![screenshot 2017-01-30 11 19 06](https://cloud.githubusercontent.com/assets/1282401/22433551/5f9ae356-e6de-11e6-8b08-b6d8965857a4.png)

**Proposed solution**
Add `margin-bottom: 20px;`
![screenshot 2017-01-30 11 20 30](https://cloud.githubusercontent.com/assets/1282401/22433554/654f1560-e6de-11e6-9320-9361ed6dc640.png)

**Comment by bspeare** [comment]
I added the margin-bottom for the people grid pane.
