### ISSUE TITLE
Clearfix panel panes

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#14]
All panel panes should be clearfix-ed to maintain a stacked layout.

Currently:
![screenshot 2017-01-30 11 24 30](https://cloud.githubusercontent.com/assets/1282401/22433776/243104fc-e6df-11e6-89c7-4d18b42317eb.png)

With clearfix:
![screenshot 2017-01-30 11 25 38](https://cloud.githubusercontent.com/assets/1282401/22433779/272c268c-e6df-11e6-8ca8-d6e019b49e05.png)

**Comment by bspeare** [comment]
I added the cf mixin to target the panes.
