### ISSUE TITLE
Greater differentiation between links and plain text

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#15]
It is difficult to distinguish links from body text because the default link color is so close to the body text color. From feedback with the Black & Gold theme I know this is going to come up from users.
![screenshot 2017-01-30 11 29 47](https://cloud.githubusercontent.com/assets/1282401/22433974/e9b97f4c-e6df-11e6-8114-8bbdf78d6b71.png)

Is there something we could change about the links in text areas to make them stand out more from the plain text?

Increase the font weight?
![screenshot 2017-01-30 11 34 05](https://cloud.githubusercontent.com/assets/1282401/22434095/53fca816-e6e0-11e6-89d5-bc63e0d8f4bd.png)

Include an underline (which would require changing the hover/focus effect)?
![screenshot 2017-01-30 11 34 23](https://cloud.githubusercontent.com/assets/1282401/22434100/57439868-e6e0-11e6-909f-47693fa9bf14.png)

Alter the color?

**Comment by bspeare** [comment]
How about increasing the font-weight to 400?
