### ISSUE TITLE
Header styles

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/sitenow_standard_lab_theme#2]
I did some very basic testing with an existing site locally. I switched into the theme and configured some basic theme settings and it appears as if there is an issue with the header. I'm attaching a screen capture.
<img width="1378" alt="screen shot 2017-01-25 at 3 31 31 pm" src="https://cloud.githubusercontent.com/assets/1016880/22310097/95c0fe76-e313-11e6-8af7-64146488a27f.png">

**Comment by adamdelaney** [comment]
After some investigation it looks like this issue was due to picking the incorrect layout from the theme settings layout extension. I'm currently logged in as an admin so I don't know if webmaster have a more limited selection. Either way we should probably be hiding all of the other layout options for that theme. I wonder if we can programmatically set the correct layout when switching themes?

**Comment by adamdelaney** [comment]
It looks like the omega extensions are not configurable by webmasters. I think we are restricting this in sitenow_core.module hook_form_alter().

**Comment by richardbporter** [comment]
I wasn't able to replicate this as a webmaster. I switched back and forth to all the allowed themes and never had a layout issue.

**Comment by adamdelaney** [comment]
I have tested this several more times and was not able to reproduce the issue. Additionally, it looks like the theme info file has the correct page layout specified, so I think we a good to close this issue.
