### ISSUE TITLE
Organize theme settings

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#24]
There are a lot of custom theme settings for the Lab theme, and the settings page is a little overwhelming right now. Some of the settings which are currently check boxes cannot be applied at the same time (but this isn't being validated).

I am proposing that the settings be separated into more field sets, and where it makes sense to use radios instead of check boxes for either/or settings.

This is a rough draft of how the form could be organized, with the Header Background Image settings displaying only if the "Header Background Image" toggle box is checked.
![theme_settings](https://cloud.githubusercontent.com/assets/1282401/22441732/3f8a10f8-e6fe-11e6-8670-cacd0b023394.jpeg)

**Comment by genjohnson** [comment]
I'm planning to work on this issue this afternoon.

**Comment by genjohnson** [comment]
@bspeare It looks like there are custom theme settings that webmasters are not allowed access to customize:
- **Remove Background Transparency** - Remove the background transparency color overlay (main_image_config_toggle_remove_transparency)
- **Site Name White Background** - Add a solid white background behind the site name (site_name_toggle_background_appearance)

If webmasters do not have access to these settings, then the sites will always use the default value for these settings (in which case it doesn't make sense to have these settings at all).

Should webmasters be able to change these settings or can these settings be removed?

**Comment by bspeare** [comment]
I left those settings in with the hope that I could use them to build sites using the administrator role for CLAS.   Is this a possibility or does the service not allow user access at the administrator level?

**Comment by genjohnson** [comment]
The SiteNow Standard service does not allow user access at the administrator level.

**Comment by genjohnson** [comment]
Ben and I chatted about how we could help site owners avoid making their websites less accessible when it comes to selecting the color & background of the site name and slogan.

We've agreed to validate the theme settings form, looking for bad color combinations. If there ends up being a wide-spread issue of site owners configuring these settings in an in-accessible way, then we will re-group to discuss how to address the issue.

**Comment by genjohnson** [comment]
I've been thinking about the logic to validate the color settings, and to make the options straight forward I recommend a minor change to a couple of the settings fields.

- Use radios (instead of a checkbox) to select the color of the site name and slogan
- Use a checkbox to select to display a box behind the site name and slogan (I think this is already in place in the feature branch 24-organize_theme_settings)
- Use radios to select the color of the box behind the site name and slogan, with this field only being displayed if the checkbox to display a box is checked.

The corresponding form validation logic would then be something like this pseudo code:
```php
if ("display a box behind the site name and slogan" == TRUE) {
    if ("color of the site name" == "color of the box") {
        form_set_error('The text color of the site name and slogan cannot be the same color as its background. Please change the color of the text or the box, or remove the box from behind the site name and slogan.');
    }
}
else { 
    if ("display a background image" == TRUE && "transparency overlay effect" != 'none') {
        if ("color of site name" == "color of transparency") {
            form_set_error('The text color of the site name and slogan cannot be the same color as its background. Please change the color of the text or the transparency overlay, or select to display a box behind the site name and slogan.');    
        }
    }
}
```

**Comment by bspeare** [comment]
Great idea on the logic.  I will continue to work on this tomorrow adjusting the css to match some of the new classes.
