### ISSUE TITLE
Add info about "Lab" theme to SiteNow website

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_lab_theme#26]
A short description and picture of each theme is included on https://sitenow.uiowa.edu/service-type/sitenow-standard. 

We should add the "Lab" theme to this page.

**Comment by genjohnson** [comment]
For reference, the demo website for this theme is https://uiowa.edu/sitenow-lab-theme/.

**Comment by bspeare** [comment]
The short description could be something like:

The Lab theme offers a customizable header region as well as a few different color options.
This theme is commonly used for the websites of research groups and labs.
